/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.starlabs.vista.administracion.clinica;

import cl.starlabs.controladores.ClinicaJpaController;
import cl.starlabs.controladores.SucursalJpaController;
import cl.starlabs.controladores.exceptions.IllegalOrphanException;
import cl.starlabs.modelo.Clinica;
import cl.starlabs.modelo.Sucursal;
import java.awt.Color;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Victor Manuel Araya
 */
public class AdministracionClinica extends javax.swing.JFrame {

    EntityManagerFactory emf = null;
    Sucursal suc = null;
    boolean editar = false;
    
    public AdministracionClinica() {
        initComponents();
        //centrando ventana
        this.setLocationRelativeTo(null);
        //persistencia
        emf = Persistence.createEntityManagerFactory("SyncPetPU");
        //prueba
        suc = new SucursalJpaController(emf).findSucursal(1);
        //definiendo estado de campos por defecto
        txtNombreFantasia.setEditable(false);
        txtNombreFantasia.setText(suc.getClinica().getNombreFantasia());
        txtNombreReal.setEditable(false);
        txtNombreReal.setText(suc.getClinica().getNombreReal());
        txtRut.setEditable(false);
        txtRut.setText(cl.starlabs.herramientas.HerramientasRut.formatear(suc.getClinica().getRut()+"-"+suc.getClinica().getDv()));
    }

    public AdministracionClinica(Sucursal suc) {
        initComponents();
        //centrando ventana
        this.setLocationRelativeTo(null);
        //definir sucursal
        this.suc = suc;
        //definiendo estado de campos por defecto
        txtNombreFantasia.setEditable(false);
        txtNombreFantasia.setText(suc.getClinica().getNombreFantasia());
        txtNombreReal.setEditable(false);
        txtNombreReal.setText(suc.getClinica().getNombreReal());
        txtRut.setEditable(false);
        txtRut.setText(cl.starlabs.herramientas.HerramientasRut.formatear(suc.getClinica().getRut()+"-"+suc.getClinica().getDv()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtNombreFantasia = new javax.swing.JTextField();
        txtNombreReal = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtRut = new javax.swing.JTextField();
        btnAccion = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SyncPet :: Administración de Datos de Clínica");
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Información de mi clínica"));

        jLabel1.setText("Nombre de Fantasía");

        jLabel2.setText("Nombre Real");

        jLabel3.setText("Rut de la empresa");

        txtRut.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRutFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreFantasia)
                    .addComponent(txtNombreReal)
                    .addComponent(txtRut))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombreReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAccion.setText("Editar");
        btnAccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccionActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cerrar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(btnAccion, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccion)
                    .addComponent(btnCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccionActionPerformed
        if(!editar) {
            txtNombreFantasia.setEditable(true);
            txtNombreReal.setEditable(true);
            txtRut.setEditable(true);
            txtNombreFantasia.requestFocus();
            editar = true;
            btnAccion.setText("Guardar");
            btnCancelar.setText("Cancelar");
        }else{
            txtNombreFantasia.setEditable(false);
            txtNombreReal.setEditable(false);
            txtRut.setEditable(false);
            editar = false;
            btnAccion.setText("Editar");
            btnCancelar.setText("Cerrar");
            
            if(txtRut.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "El campo de rut se encuentra vacío");
                txtRut.requestFocus();
            }else{
                if(!cl.starlabs.herramientas.HerramientasRut.validar(txtRut.getText())) {
                    JOptionPane.showMessageDialog(null, "El rut no es valido");
                    txtRut.requestFocus();
                }else{
                    if(txtNombreFantasia.getText().isEmpty()) {
                        JOptionPane.showMessageDialog(null, "Debe especificar el nombre de fantasía de la empresa");
                        txtNombreFantasia.requestFocus();
                    }else{
                        if(txtNombreReal.getText().isEmpty()) {
                            JOptionPane.showMessageDialog(null, "Debe especificar el nombre real de la empresa");
                            txtNombreReal.requestFocus();
                        }else{
                            //todo correcto
                            try {
                                new ClinicaJpaController(emf).actualizar(new Clinica(suc.getClinica().getIdClinica(), txtNombreFantasia.getText(), txtNombreReal.getText(), Integer.parseInt(((txtRut.getText().replace(".", "")).split("-")[0])), (txtRut.getText().split("-")[0]).charAt(0)));
                                JOptionPane.showMessageDialog(null, "Datos actualizados con éxito");
                            } catch (Exception e) {
                                JOptionPane.showMessageDialog(null, "Ocurrió un error al actualizar los datos: "+e.getMessage());
                            }
                        }
                    }
                }
            }
        }
    }//GEN-LAST:event_btnAccionActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        if(!editar) {
            txtNombreFantasia.setEditable(true);
            txtNombreReal.setEditable(true);
            txtRut.setEditable(true);
            txtNombreFantasia.requestFocus();
            editar = true;
            btnAccion.setText("Guardar");
            btnCancelar.setText("Cancelar");
            this.dispose();
        }else{
            txtNombreFantasia.setEditable(false);
            txtNombreReal.setEditable(false);
            txtRut.setEditable(false);
            editar = false;
            btnAccion.setText("Editar");
            btnCancelar.setText("Cerrar");
        }
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtRutFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRutFocusLost
        if(!txtRut.getText().isEmpty()) {
            //formateando
            txtRut.setText(cl.starlabs.herramientas.HerramientasRut.formatear(txtRut.getText()));
            //validando
            if(cl.starlabs.herramientas.HerramientasRut.validar(txtRut.getText())) {
                txtRut.setForeground(Color.black);
                txtRut.setBackground(Color.white);
                btnAccion.setEnabled(true);
                btnAccion.requestFocus();
            }else{
                txtRut.setForeground(Color.white);
                txtRut.setBackground(Color.red);
                txtRut.requestFocus();
                btnAccion.setEnabled(false);
            }
        }
    }//GEN-LAST:event_txtRutFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministracionClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministracionClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministracionClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministracionClinica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionClinica().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccion;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNombreFantasia;
    private javax.swing.JTextField txtNombreReal;
    private javax.swing.JTextField txtRut;
    // End of variables declaration//GEN-END:variables
}
