/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cl.starlabs.vista.login;

import cl.starlabs.modelo.Usuarios;
import cl.starlabs.vista.principal.PrincipalAdmin;
import cl.starlabs.vista.principal.PrincipalMedico;
import cl.starlabs.vista.principal.PrincipalRecepcionista;
import javax.swing.JOptionPane;

/**
 *
 * @author Janno
 */
public class PantallaBloqueo extends javax.swing.JFrame {

    /**
     * Creates new form PantallaBloqueo
     */
    PrincipalAdmin pa           = null;
    PrincipalMedico pm          = null;
    PrincipalRecepcionista pr   = null;
    Usuarios us                 = null;
    
    public PantallaBloqueo() {
        initComponents();
        //centrando ventana
        this.setLocationRelativeTo(null);
    }
    
    public PantallaBloqueo(PrincipalAdmin pa, Usuarios us) {
        initComponents();
        //centrando ventana
        this.setLocationRelativeTo(null);
        //obteniendo valores de ventana
        this.pa = pa;
        this.us = us;
        //Seteando el valor del label
        lblNombreDeUsuario.setText(us.getUsuario()+" ("+us.getNombres().split(" ")[0]+" "+us.getApaterno()+") <<"+us.getDetalleUsuariosList().get(0).getSucursal().getClinica().getNombreReal()+">>");
    }
    
    
    public PantallaBloqueo(PrincipalMedico pm, Usuarios us) {
        initComponents();
        //centrando ventana
        this.setLocationRelativeTo(null);
        //obteniendo valores de ventana
        this.pm = pm;
        this.us = us;
        //Seteando el valor del label
        lblNombreDeUsuario.setText(us.getUsuario()+" ("+us.getNombres().split(" ")[0]+" "+us.getApaterno()+") <<"+us.getDetalleUsuariosList().get(0).getSucursal().getClinica().getNombreReal()+">>");
    }
    
    
    public PantallaBloqueo(PrincipalRecepcionista pr, Usuarios us) {
        initComponents();
        //centrando ventana
        this.setLocationRelativeTo(null);
        //obteniendo valores de ventana
        this.pr = pr;
        this.us = us;
        //Seteando el valor del label
        lblNombreDeUsuario.setText(us.getUsuario()+" ("+us.getNombres().split(" ")[0]+" "+us.getApaterno()+") <<"+us.getDetalleUsuariosList().get(0).getSucursal().getClinica().getNombreReal()+">>");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNombreDeUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtContrasena = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SyncPet :: Terminal Bloqueado");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/imagenes/sistema/logo aplicacion slide.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("El terminal se encuentra temporalmente bloqueado. Por favor vuelva a ingresar su contraseña:");

        lblNombreDeUsuario.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        lblNombreDeUsuario.setText("Nombre de Usuario no especificado");

        jLabel3.setText("Contraseña");

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cl/starlabs/imagenes/iconos/icon_padlock.gif"))); // NOI18N
        jButton2.setText("Desbloquear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2))
                            .addComponent(lblNombreDeUsuario))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombreDeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if(txtContrasena.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe escribir la contraseña del usuario "+us.getUsuario()+" para desbloquear el terminal");
            txtContrasena.requestFocus();
        }else{
            if(txtContrasena.getText().compareTo(us.getContrasena()) == 0) {
                if(pm != null) {
                    pm.setVisible(true);
                    this.dispose();
                    pm = null;
                }else if(pa != null) {
                    pa.setVisible(true);
                    this.dispose();
                    pa = null;
                }else if(pr != null) {
                    pr.setVisible(true);
                    this.dispose();
                    pr = null;
                }
            }else{
                JOptionPane.showMessageDialog(null, "Contraseña Incorrecta");
                txtContrasena.requestFocus();
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaBloqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaBloqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaBloqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaBloqueo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaBloqueo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblNombreDeUsuario;
    private javax.swing.JPasswordField txtContrasena;
    // End of variables declaration//GEN-END:variables
}
